[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
equity_vault = "8NhtqxR1mwq7a3HTUtcGABNZ3KWzQi9KM3fXu3rHS8LH"

[programs.devnet]
equity_vault = "8NhtqxR1mwq7a3HTUtcGABNZ3KWzQi9KM3fXu3rHS8LH"

[programs.mainnet]
equity_vault = "8NhtqxR1mwq7a3HTUtcGABNZ3KWzQi9KM3fXu3rHS8LH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsc && npx mocha -t 1000000 tests/anchor/**/*.js"
