//! Core domain types for Equity Catalyst.

use serde::{Deserialize, Serialize};
use std::fmt;

use crate::constants::MAX_BPS;
use crate::validation::{self, ValidationError};

/// Explicit newtype wrapper around a Unix timestamp in seconds.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct UnixSeconds(pub i64);

impl UnixSeconds {
    pub const ZERO: Self = Self(0);

    pub fn as_i64(self) -> i64 {
        self.0
    }
}

impl From<i64> for UnixSeconds {
    fn from(s: i64) -> Self {
        Self(s)
    }
}

impl From<UnixSeconds> for i64 {
    fn from(u: UnixSeconds) -> Self {
        u.0
    }
}

impl fmt::Display for UnixSeconds {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Represents a fractional value in basis points (1 bp = 0.01% = 0.0001).
/// 10,000 bps represents 100.00%.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct BasisPoints(pub u16);

impl BasisPoints {
    pub const ZERO: Self = Self(0);
    pub const MAX: Self = Self(MAX_BPS);

    pub fn new(bps: u16) -> Result<Self, ValidationError> {
        if bps > MAX_BPS {
            return Err(ValidationError::InvalidBasisPoints(bps));
        }
        Ok(Self(bps))
    }

    pub fn as_bps(self) -> u16 {
        self.0
    }

    pub fn to_percentage_f64(self) -> f64 {
        (self.0 as f64) / 100.0
    }

    pub fn is_valid(self) -> bool {
        self.0 <= MAX_BPS
    }
}

impl fmt::Display for BasisPoints {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:.2}% ({} bps)", self.to_percentage_f64(), self.0)
    }
}

/// Portfolio risk boundary constraints.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct RiskLimits {
    pub min_cash_bps: BasisPoints,
    pub max_position_bps: BasisPoints,
    pub max_slippage_bps: BasisPoints,
}

impl Default for RiskLimits {
    fn default() -> Self {
        Self {
            min_cash_bps: BasisPoints(1_000),     // 10.00% unencumbered cash
            max_position_bps: BasisPoints(2_500), // 25.00%
            max_slippage_bps: BasisPoints(100),   // 1.00%
        }
    }
}

/// Market and event signals generated by policy engines.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SignalType {
    Bullish,
    Bearish,
    Neutral,
    RebalanceRequired,
    EmergencyExit,
}

/// Individual asset target allocation weight.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AssetWeight {
    pub symbol: String,
    pub target_weight: BasisPoints,
}

/// Portfolio target allocation target ensuring sum to 10,000 bps.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AllocationTarget {
    pub weights: Vec<AssetWeight>,
}

impl AllocationTarget {
    pub fn new(weights: Vec<AssetWeight>) -> Result<Self, ValidationError> {
        validation::validate_weights_sum(&weights)?;
        Ok(Self { weights })
    }

    pub fn total_weight_bps(&self) -> u16 {
        self.weights.iter().map(|w| w.target_weight.0).sum()
    }

    pub fn get_weight(&self, symbol: &str) -> Option<BasisPoints> {
        self.weights
            .iter()
            .find(|w| w.symbol == symbol)
            .map(|w| w.target_weight)
    }
}

/// Snapshot of an individual active position.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PositionSnapshot {
    pub symbol: String,
    pub current_amount: u64,
    pub entry_price_usd: u64,
    pub current_price_usd: u64,
    pub current_value_usd: u64,
}
